### PR TITLE
release 8.0.0

### PR DESCRIPTION
**Pull request by staltz**
What to review here? Whether y'all consider this a breaking change version or not, and the new CHANGELOG file.

Upon merging, I (or anyone with rights) can npm publish.

### CODE REVIEW

**Comment by christianbundy** [comment]
> Node.js versions lower than 5.10.0 are not supported anymore

Smells like a breaking change to me. I'm on my phone and can't publish, but I'll approve.

**Review by christianbundy — APPROVED** [review]
Affirmative. Also I love this release PR process, seems great.

**Comment by arj03** [comment]
Maybe I'm out of the loop, but why not chloride 2.3?

**Comment by staltz** [comment]
@arj03 https://github.com/ssb-js/ssb-keys/pull/71

**Comment by staltz** [comment]
@arj03 Here are the test failures specifically: https://travis-ci.com/github/ssb-js/ssb-keys/jobs/389293787

**Pull request merged**
